version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - 8080:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - httpbin
  httpbin:
    image: kennethreitz/httpbin

