version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - 8080:80
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    depends_on:
      - http-server
  proxy-keepalive:
    build: ./proxy-keepalive
    ports:
      - 8082:80
    volumes:
      - ./proxy-keepalive/conf.d:/etc/nginx/conf.d
    depends_on:
      - http-server
  http-server:
    build: ./http-server
    volumes:
      - ./http-server/conf.d:/etc/nginx/conf.d
    ports:
      - 8081:80
